# Generated by Django 2.2.5 on 2021-08-10 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_fund', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('bitcoin', 'bitcoin'), ('etherium', 'etherium'), ('BNB', '   BNB')], default='bitcoin', max_length=10)),
                ('deposit_status', models.CharField(choices=[('approved', 'approved'), ('cancelled', 'cancelled'), ('pending', 'pending')], default='pending', max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.CharField(default='vip', max_length=10)),
                ('invested_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=50)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('time_left', models.DurationField()),
                ('duration', models.IntegerField(default=7)),
                ('daily_percent', models.IntegerField(default=0)),
                ('timer', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default=None, max_length=50)),
                ('plan_daily_percentage', models.IntegerField(default=0)),
                ('days_duration', models.IntegerField(default=0)),
                ('minimum_deposit', models.IntegerField(default=0)),
                ('maximum_deposit', models.IntegerField(default=0)),
                ('expected_returns', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TheMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_balance', models.IntegerField(default=0)),
                ('earning_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_withdraw', models.IntegerField(default=0)),
                ('withdrawal_status', models.CharField(choices=[('approved', 'approved'), ('cancelled', 'cancelled'), ('pending', 'pending')], default='pending', max_length=50)),
                ('method', models.CharField(choices=[('bank', 'bank'), ('bitcoin', 'bitcoin'), ('etherium', 'etherium'), ('BNB', 'BNB')], default='bitcoin', max_length=12)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
