# Generated by Django 3.2.3 on 2021-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_status',
            field=models.CharField(choices=[('approved', 'approved'), ('cancelled', 'cancelled'), ('pending', 'pending')], default='ongoing', max_length=50),
        ),
    ]
