# Generated by Django 3.2.3 on 2021-08-30 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20210830_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ref',
            new_name='TheRef',
        ),
    ]
