# Generated by Django 3.2.3 on 2021-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_ref_theref'),
    ]

    operations = [
        migrations.AddField(
            model_name='themain',
            name='ref_balance',
            field=models.IntegerField(default=0),
        ),
    ]
