# Generated by Django 3.2.3 on 2021-09-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_themain_ref_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='themain',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fund_account'),
        ),
        migrations.AddField(
            model_name='themain',
            name='invest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invest'),
        ),
    ]
