# Generated by Django 3.2.3 on 2021-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_rename_recommend_referral_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
