# Generated by Django 2.2.5 on 2021-08-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='_blog')),
                ('authur', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=20)),
                ('short_content', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='_testimony')),
                ('comment', models.CharField(max_length=20)),
                ('Occupation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='_investor')),
                ('comment', models.CharField(max_length=30)),
                ('head', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='_members')),
            ],
        ),
        migrations.CreateModel(
            name='TopInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('invested_amount', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='_investor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='_transact')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='_transact')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
