# Generated by Django 3.2.3 on 2021-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred',
            field=models.BooleanField(default=False),
        ),
    ]
