# Generated by Django 3.2.3 on 2021-08-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_referred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referred',
            new_name='approve_broker',
        ),
    ]
