# Generated by Django 3.2.5 on 2021-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_referred_user_approve_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='bank',
            name='account_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
